spring:
    datasource:
        url: jdbc:mysql://192.168.81.142:3306/tickect?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123321
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
    resources:
        add-mappings: false
    application:
        name: automic-order-service
    profiles:
        active: develop
        default: develop
mybatis:
     mapper-locations: classpath:mapping/**/*.xml
     config-location: classpath:mybatis-config.xml
     type-aliases-package: com.tiantian.ticket.model
server:
    port: 8081
